package io.github.priospot.cli

import io.github.priospot.model.ModelJson
import io.github.priospot.model.PanopticodeDocument
import io.github.priospot.report.svg.ReportType
import io.github.priospot.report.svg.SvgTreemapReporter
import java.nio.file.Files
import java.nio.file.Path
import java.util.concurrent.Callable
import picocli.CommandLine

@CommandLine.Command(
    name = "report",
    description = ["Generate one interactive treemap SVG from an existing panopticode JSON file."],
)
class ReportCommand : Callable<Int> {
    @CommandLine.Option(
        names = ["--input-json"],
        required = true,
        description = ["Input panopticode JSON generated by the analyze command."],
        paramLabel = "<path>",
    )
    lateinit var inputJson: String

    @CommandLine.Option(
        names = ["--type"],
        required = true,
        description = ["Treemap type: priospot, coverage, complexity, or churn."],
        paramLabel = "<type>",
    )
    lateinit var type: String

    @CommandLine.Option(
        names = ["--output-svg"],
        required = true,
        description = ["Output SVG path for the generated interactive treemap."],
        paramLabel = "<path>",
    )
    lateinit var outputSvg: String

    override fun call(): Int {
        val doc =
            ModelJson.mapper.readValue(
                Files.readString(Path.of(inputJson)),
                PanopticodeDocument::class.java,
            )
        val reportType =
            when (type.lowercase()) {
                "priospot" -> ReportType.PRIOSPOT
                "coverage" -> ReportType.COVERAGE
                "complexity" -> ReportType.COMPLEXITY
                "churn" -> ReportType.CHURN
                else -> error("Unsupported report type")
            }

        SvgTreemapReporter().generateInteractiveTreemap(doc.project, reportType, Path.of(outputSvg))
        println("Generated $outputSvg")
        return 0
    }
}
